#!/bin/sh

if ! test -d .git; then
    echo "Execute scripts/install-git-hooks in the top-level directory."
    exit 1
fi

ln -sf ../../scripts/pre-commit.sh .git/hooks/pre-commit || exit 1
chmod +x .git/hooks/pre-commit

ln -sf ../../scripts/commit-msg.sh .git/hooks/commit-msg || exit 1
chmod +x .git/hooks/commit-msg

echo
echo "Git hooks are installed successfully."
